# Generated by Django 3.0 on 2021-05-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="upload_to='/pdfs"),
        ),
    ]
